== 動作環境の構築

周辺ツールである `nem-sdk` と `nem2-cli` はJavaScriptで記述されたツールです。
動作環境に `Node.js` をインストールして、ツールのインストールを行います。

=== Node.jsのインストール

Node.jsは公式のインストーラや `nodenv` などのバージョンマネージャなどを用いてインストールして、コマンドパスが通っている状態にしてください。

* https://nodejs.org/ja/[Node.js]
* https://github.com/nodenv/nodenv[nodenv/nodenv: Manage multiple NodeJS versions.]

コマンドパスが通っており、バージョンが確認できる状態にしてください。

[source,shell]
----
$ node -v
v10.17.0
----


=== nem2-cliのインストール

`nem2-cli` はNEMネットワークからアカウントやトランザクションの情報を取得したり、トランザクションを発信するコマンドラインツールです。
グローバルインストールをして、コマンドパスが通っている状態にしてください。

[source,shell]
----
$ npm install nem2-cli@0.14.0 -g
$ nem2-cli
                        ____            _ _
   _ __   ___ _ __ ___ |___ \       ___| (_)
  | '_ \ / _ \ '_ ` _ \  __) |____ / __| | |
  | | | |  __/ | | | | |/ __/_____| (__| | |
  |_| |_|\___|_| |_| |_|_____|     \___|_|_|

                                     v0.14.0
----


=== nem2-sdkのインストール

`nem2-sdk` はAPIとの疎通やトランザクションの作成をJavaScriptで行える開発用ライブラリです。
`scripts/` ディレクトリへ移動して、モジュールのインストールを行ってください。

[source,shell]
----
$ cd scripts
$ npm install
----


=== コードを実行する前に

サンプルコードは `PRIVATE_KEY` と `GENERATION_HASH` を環境変数から取得します。
`NETWORK_TYPE` と `API_URL` はデフォルト値を設定しますが、変更が必要な場合は設定してください。

[source,shell]
----
export PRIVATE_KEY=C2337B8926ED13EA2C481AB559FFD716E5C3AD76273759B4F7A0DB9315745972
export GENERATION_HASH=0EE13AFBE49394B9985DB8AF1BBCD98859BA9277ACF3A413D639D9C8D76D538F

# デフォルトでは次が設定されます。変更したい場合に設定してください。
# export API_URL=http://localhost:3000
# export NETWORK_TYPE=MIJIN_TEST
----

[source,shell]
----
$ source ./env
----

`PRIVATE_KEY`, `GENERATION_HASH` は `alice` のプロファイルから確認してください。

[source,shell]
----
$ nem2-cli profile list
alice->
	Network:	MIJIN_TEST
	Url:		http://localhost:3000
	GenerationHash:	0EE13AFBE49394B9985DB8AF1BBCD98859BA9277ACF3A413D639D9C8D76D538F
	Address:	SDUCBSRYQTSWEGAOZWYO6AAKBSM6LVON7E5WBHVQ
	PublicKey:	B775E5DCDF76959B9F5769DD2E9F873A0C7E5F9C9073837AF7850057EA90B20B
	PrivateKey:	C2337B8926ED13EA2C481AB559FFD716E5C3AD76273759B4F7A0DB9315745972
----

なお `GenerationHash` は http://localhost:3000/block/1 のレスポンスに含まれる `generationHash` の値です。
プログラムなどで動的に取得したい場合はAPIゲートウェイから取得できます。

.初期ブロック例（整形済み） http://localhost:3000/block/1
[source,shell]
----
{ "meta": {
"hash":"7001FA2FF43AF77BBA5CFB56A87FCDCAA4E64161DA9E1A250B5AEB03EEA36327",
"generationHash":"0EE13AFBE49394B9985DB8AF1BBCD98859BA9277ACF3A413D639D9C8D76D538F"
(省略)
----
