== はじめに

`Symbol` とは `NEM` の次期バージョンです。関連ソフトウェアはGitHubにオープンソースとして公開されています。

2019年12月にNEM公式による開発用テストネットワーク `TESTNET` が公開されました。
このテストネットを利用するか、ローカルマシンに独自ネットワークを構築する方法で `Symbol` ネットワークを操作することができます。

リリース予定の機能が実装され、最終テスト段階となりましたが、SDKの仕様などは変わる可能性があります。

本章では、いずれかのノードネットワークに接続して、 `Symbol` の機能を動作させる具体的なコードを実行しながら、動作と機能の学習を進めます。

本プロジェクトのサンプルコードは挙動の確認を優先するため、現実の実用には不向きな部分があります。
本プロジェクトで扱っている仕様が無意味なものになるかもしれない程度に、今後において追加変更される場合が考えられます。

=== 動作環境について

.本章で使用する各ソフトウェアのバージョン
[cols="h,d" options="autowidth"]
|===
|macOS|High Sierra	10.13.6
|Node.js|10.17.0
|nem2-cli|0.14.0
|nem2-sdk|0.15.0
|===

.ローカルネットワークを構築する場合に使用するソフトウェア
[cols="h,d" options="autowidth"]
|===
|Docker|version 19.03.2, build 6a30dfc
|Docker Compose|version 1.24.1, build 4667896b
|symbol-service-bootstrap|0.9.0.1
|===

メジャーバージョンが大きく異なっていなければ、これらのバージョン以外でなくとも動作すると思われますが、問題が発生する場合は上記に合わせてください。

特に `nem2-cli`, `nem2-sdk`, `symbol-service-bootstrap` の組み合わせについて、APIゲートウェイのレスポンススキーマの差異によって正常に動作しない場合があります。

`macOS` 上で動作させた内容のため `Windows` や `Linux` 環境で行う場合はコマンドライン操作が異なる場合があります。
適宜読み替えて操作を行ってください。
